version: '3.8'

services:
  # O Banco de Dados
  db:
    image: postgres:15
    container_name: talkandbet_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: talkandbet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Ferramenta para você ver o banco pelo navegador
  pgadmin:
    image: dpage/pgadmin4
    container_name: talkandbet_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: